import React, { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { CheckSquare, Plus } from 'lucide-react';
import { supabase } from '@/api/supabaseClient';
import { useUser } from '@/components/hooks/useUser';
import { ProtectedRoute } from '@/components/common/ProtectedRoute';
import PageHeader from '@/components/common/PageHeader';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from '@/components/ui/sheet';
import { toast } from 'sonner';
import { usePagination } from '@/components/common/usePagination';
import PaginationBar from '@/components/common/PaginationBar';

const empty = { title: '', problem: '', cause: '', action: '', responsible_user_id: '', due_date: '', priority: 'medium', status: 'todo', expected_result: '', actual_result: '', baseline_value: '', target_value: '', measurement_unit: '' };
export default function ActionPlans() {
  const { user } = useUser(); const companyId = user?.active_company_id; const queryClient = useQueryClient(); const [open, setOpen] = useState(false);
  const { data: plans = [], isLoading } = useQuery({ queryKey: ['performance-action-plans', companyId], queryFn: async () => { const { data, error } = await supabase.from('performance_action_plans').select('*').eq('company_id', companyId).order('due_date'); if (error) throw error; return data; }, enabled: !!companyId });
  const save = useMutation({ mutationFn: async (plan) => { const { error } = await supabase.from('performance_action_plans').insert({ ...plan, company_id: companyId, responsible_user_id: plan.responsible_user_id || null, due_date: plan.due_date || null }); if (error) throw error; }, onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['performance-action-plans', companyId] }); setOpen(false); toast.success('Plan d’action créé'); }, onError: (error) => toast.error(error.message || 'Plan non créé') });
  const updateStatus = useMutation({ mutationFn: async ({ plan, status }) => { const { error } = await supabase.from('performance_action_plans').update({ status }).eq('id', plan.id).eq('company_id', companyId); if (error) throw error; }, onSuccess: () => queryClient.invalidateQueries({ queryKey: ['performance-action-plans', companyId] }) });
  const updateMeasurement = useMutation({ mutationFn: async ({ plan, actual_value }) => { const { error } = await supabase.from('performance_action_plans').update({ actual_value: Number(actual_value), measured_at: new Date().toISOString().slice(0, 10) }).eq('id', plan.id).eq('company_id', companyId); if (error) throw error; }, onSuccess: () => queryClient.invalidateQueries({ queryKey: ['performance-action-plans', companyId] }) });
  const { paginatedItems: pagedPlans, currentPage, totalPages, totalItems, goToPrevious, goToNext } = usePagination(plans, 10);
  return <ProtectedRoute><div className="space-y-6"><PageHeader title="Plans d’action" subtitle="Transformez les écarts en actions mesurables." actions={<Button onClick={() => setOpen(true)} className="gap-2"><Plus className="h-4 w-4" />Nouvelle action</Button>} /><Card><CardHeader><CardTitle className="flex items-center gap-2"><CheckSquare className="h-5 w-5" />Suivi des actions</CardTitle></CardHeader><CardContent className="p-0">{isLoading ? <p className="p-6">Chargement...</p> : plans.length === 0 ? <p className="py-8 text-center text-sm text-slate-500">Aucun plan d’action.</p> : <div className="divide-y">{pagedPlans.map((plan) => <div key={plan.id} className="flex flex-wrap items-start gap-4 p-4"><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2"><p className="font-semibold">{plan.title}</p><Badge variant="outline">{plan.priority}</Badge><Badge variant="secondary">{plan.status}</Badge></div><p className="mt-1 text-sm text-slate-600">Problème : {plan.problem}</p><p className="text-sm text-slate-600">Action : {plan.action}</p><p className="mt-1 text-xs text-slate-500">Échéance : {plan.due_date || 'non définie'} · Résultat attendu : {plan.expected_result || '—'}</p><p className="text-xs text-slate-500">Avant : {plan.baseline_value ?? '—'} · Cible : {plan.target_value ?? '—'} · Après : {plan.actual_value ?? 'À mesurer'} {plan.measurement_unit || ''}</p>{plan.baseline_value !== null && plan.actual_value !== null && <p className="text-xs font-medium text-emerald-700">Écart mesuré : {(Number(plan.baseline_value) - Number(plan.actual_value)).toFixed(2)} {plan.measurement_unit || ''}</p>}</div><div className="flex flex-col gap-2"><select value={plan.status} onChange={(event) => updateStatus.mutate({ plan, status: event.target.value })} className="h-9 rounded-md border px-2 text-sm"><option value="todo">À faire</option><option value="in_progress">En cours</option><option value="blocked">Bloqué</option><option value="done">Terminé</option><option value="cancelled">Annulé</option></select>{plan.actual_value === null && <Button size="sm" variant="outline" onClick={() => { const value = window.prompt('Valeur mesurée après action'); if (value !== null) updateMeasurement.mutate({ plan, actual_value: value }); }}>Mesurer</Button>}</div></div>)}</div>}</CardContent><PaginationBar currentPage={currentPage} totalPages={totalPages} totalItems={totalItems} pageSize={10} onPrevious={goToPrevious} onNext={goToNext} /></Card><ActionForm open={open} onOpenChange={setOpen} pending={save.isPending} onSubmit={(plan) => save.mutate(plan)} /></div></ProtectedRoute>;
}
function ActionForm({ open, onOpenChange, pending, onSubmit }) { const [form, setForm] = useState(empty); useEffect(() => { if (open) setForm(empty); }, [open]); const update = (field) => (event) => setForm((current) => ({ ...current, [field]: event.target.value })); const submit = (event) => { event.preventDefault(); onSubmit({ ...form, baseline_value: form.baseline_value === '' ? null : Number(form.baseline_value), target_value: form.target_value === '' ? null : Number(form.target_value) }); }; return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent className="overflow-y-auto"><SheetHeader><SheetTitle>Nouvelle action</SheetTitle><SheetDescription>Décrivez le problème, la cause, l’action et le résultat attendu.</SheetDescription></SheetHeader><form onSubmit={submit} className="mt-6 space-y-4">{[['title','Titre'],['problem','Problème'],['cause','Cause'],['action','Action'],['expected_result','Résultat attendu'],['actual_result','Résultat obtenu']].map(([field,label]) => <div className="space-y-2" key={field}><Label htmlFor={`action-${field}`}>{label}{['title','problem','action'].includes(field) ? ' *' : ''}</Label><Input id={`action-${field}`} value={form[field]} onChange={update(field)} required={['title','problem','action'].includes(field)} /></div>)}<div className="grid grid-cols-3 gap-3"><div className="space-y-2"><Label>Avant</Label><Input type="number" step="0.01" value={form.baseline_value} onChange={update('baseline_value')} /></div><div className="space-y-2"><Label>Cible</Label><Input type="number" step="0.01" value={form.target_value} onChange={update('target_value')} /></div><div className="space-y-2"><Label>Unité</Label><Input value={form.measurement_unit} onChange={update('measurement_unit')} placeholder="%, EUR..." /></div></div><div className="grid grid-cols-2 gap-4"><div className="space-y-2"><Label>Priorité</Label><select value={form.priority} onChange={update('priority')} className="flex h-9 w-full rounded-md border px-2 text-sm"><option value="low">Faible</option><option value="medium">Moyenne</option><option value="high">Haute</option><option value="critical">Critique</option></select></div><div className="space-y-2"><Label>Échéance</Label><Input type="date" value={form.due_date} onChange={update('due_date')} /></div></div><Button type="submit" disabled={pending} className="w-full">{pending ? 'Enregistrement...' : 'Créer le plan'}</Button></form></SheetContent></Sheet>; }
